import React, { useRef, useState, useEffect } from 'react'
// import './App.css';
import { useMediaQuery } from 'react-responsive'
import Header from "./Header"
import Footer from "./footer.js"

function App() {
  const isTabletOrMobile = useMediaQuery({ query: '(max-width: 600px)' })
  useEffect(() => {
    window.scrollTo(0,0);
  }, [])
  const data = () => {
    return (
        <React.Fragment>
        <Header style={{top: "0px !important"}} />
        <center style={{marginTop: 100}}>
          <h2>Privacy Policy</h2>
          <div style={{ width: isTabletOrMobile ? "90%" : "60%" }}>
            <p dir="ltr" className="docCss"><span className="docSpan">THIS PRIVACY POLICY IS AN ELECTRONIC RECORD IN THE FORM OF AN ELECTRONIC CONTRACT FORMED UNDER THE INFORMATION TECHNOLOGY ACT, 2000 AND THE RULES MADE THEREUNDER AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC DOCUMENTS / RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS PRIVACY POLICY DOES NOT REQUIRE ANY PHYSICAL, ELECTRONIC OR DIGITAL SIGNATURE.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">THIS DOCUMENT IS PUBLISHED AND SHALL BE CONSTRUED IN ACCORDANCE WITH THE PROVISIONS OF THE INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OF INFORMATION) RULES, 2011 UNDER INFORMATION TECHNOLOGY ACT, 2000; THAT REQUIRE PUBLISHING OF THE PRIVACY POLICY FOR COLLECTION, USE, STORAGE AND TRANSFER OF SENSITIVE PERSONAL DATA OR INFORMATION.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">THIS PRIVACY POLICY IS A LEGALLY BINDING DOCUMENT BETWEEN YOU AND GENIO (BOTH TERMS DEFINED BELOW). THE TERMS OF THIS PRIVACY POLICY WILL BE EFFECTIVE UPON YOUR ACCEPTANCE OF THE SAME (DIRECTLY OR INDIRECTLY IN ELECTRONIC FORM, BY CLICKING ON THE &ldquo;I ACCEPT&rdquo; TAB OR BY USE OR THE SERVICES OR BY OTHER MEANS) AND WILL GOVERN THE RELATIONSHIP BETWEEN YOU AND GENIO FOR YOUR USE OF THE SERVICES, MOBILE APPLICATION OR OTHER SERVICES (DEFINED BELOW).</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY USING THE SERVICES, MOBILE APPLICATION OR OTHER SERVICES, YOU INDICATE THAT YOU UNDERSTAND, AGREE AND CONSENT TO THIS PRIVACY POLICY. IF YOU DO NOT AGREE WITH THE TERMS OF THIS PRIVACY POLICY, PLEASE DO NOT USE THIS SERVICES. YOU HEREBY PROVIDE YOUR UNCONDITIONAL CONSENT OR AGREEMENTS TO GENIO AS PROVIDED UNDER SECTION 43A AND SECTION 72A OF INFORMATION TECHNOLOGY ACT, 2000.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">By providing Us Your Information or by making use of the facilities provided by the Services, Mobile Application or Other Services, you hereby consent to the collection, storage, processing and transfer of any or all of Your Personal Information and Non-Personal Information by Genio as specified under this Privacy Policy. You further agree that such collection, use, storage and transfer of Your Information shall not cause any loss or wrongful gain to You or any other person.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">Genio (&ldquo;Genio&rdquo; or &ldquo;We&rdquo; or &ldquo;Us&rdquo; or &ldquo;Our&rdquo;) is concerned about the privacy of the data and information of users (&ldquo;You&rdquo;or &ldquo;Your&rdquo; or &ldquo;Yourself&rdquo;) accessing the services on Genio&rsquo;s Services, mobile sites or mobile applications (&ldquo;Services&rdquo;).</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">This Privacy Policy is a contract between You and Genio. This Privacy Policy shall be read together with the respective Terms of Use or other terms and condition of Genio&rsquo;s Services.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">This Privacy Policy is designed to tell You about Our practices regarding collection, use, and disclosure of information or data that You may provide via this Services. Please be sure to read this entire Privacy Policy before using or submitting information to this Services.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">COLLECTION AND STORAGE OF INFORMATION 1.1. The Information (which shall also include data) provided by You to Genio or collected from You by Genio may consist of &ldquo;Personal Information&rdquo; and &ldquo;Non-Personal Information&rdquo;.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.2. Personal Information is Information collected that can be used to uniquely identify or contact You. Personal Information for the purposes of this Privacy Policy shall include, but not be limited to Your name, address, contact number, e-mail address or other contact information, company name, Information regarding your transactions on the Services, Your financial information (if applicable for purchases made on Genio), Internet Protocol address, Any other items of &ldquo;sensitive personal data or information&rdquo; as such term is defined under the Information Technology (Reasonable Security Practices And Procedures And Sensitive Personal Data Of Information) Rules, 2011 enacted under the Information Technology Act, 2000, Identification code of Your communication device which You use to access the Services or any other Information that You provide during Your registration process, if any, on the Services.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.3. Such Personal Information may be collected in various ways including during the course of You registering as a user on the Services, registering as a merchant / customer on the Services, availing certain services offered on the Services. Such instances include but are not limited to participating in any online survey or contest or otherwise or posting user reviews or otherwise doing any activities on the Services.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.4. We may receive Personal information about You from third parties, such as social media services, commercially available sources and business partners. If you access our Services through any social media service or connect our Services to a social media service, the information We collect may include Your user name associated with that social media service, any information or content the social media service has the right to share with Us, such as Your profile picture, email address or friends list, and any information You have made public in connection with that social media service. When You access the Services through social media services or when You connect Services to social media services, You are authorizing Genio to collect, store, and use and retain such information and content in accordance with this Privacy Policy.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.5. Genio may also collect information other than Personal Information from You through the Services when You visit and / or use the Services. Such information may be stored in server logs. This Non-Personal Information may include but not limited to Your geographic location, details of Your telecom service provider or internet service provider, the type of browser (Internet Explorer, Firefox, Opera, Google Chrome etc.), the operating system of Your system, device and the Services You last visited before visiting the Services or the duration of Your stay on the Services is also stored in the session along with the date and time of Your access.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.6. Non-Personal Information is collected through various ways such as through the use of cookies. Genio may store temporary or permanent &ldquo;cookies&rdquo; on Your computer. You can erase or choose to block these cookies from Your computer. You can configure Your computer&rsquo;s browser to alert You when We attempt to send You a cookie with an option to accept or refuse the cookie. If You have turned cookies off, You may be prevented from using certain features of the Services.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.7. Please do note that Personal Information and Non Personal Information may be treated differently as per this Privacy Policy.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.8. You hereby represent to Genio that:-</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">the Information You provide from time to time is and shall be authentic, correct, current and updated and You have all the rights, permissions and consents as may be required to provide such Information to Genio. Your providing the Information to Genio and Genio&rsquo;s consequent storage, collection, usage, transfer, access or processing of the same shall not be in violation of any third party agreement, laws, charter documents, judgments, orders and decrees.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.9. Genio and its officers, directors, contractors or agents shall not be responsible for the authenticity of the Information that You or any other user provide to Genio. You shall indemnify and hold harmless Genio and its officers, directors, contractors or agents and any third party relying on the Information provided by You in the event You are in breach of this Privacy Policy including this provision and the immediately preceding provision above.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">1.10. Your Information will primarily be stored in electronic form however certain data can also be stored in physical form. We may store, collect, process and use your data in countries other than Republic of India but under compliance with applicable laws. We may enter into agreements with third parties (in or outside of India) to store or process your information or data. These third parties may have their own security standards to safeguard your information or data and we will on commercial reasonable basis require from such third parties to adopt reasonable security standards to safeguard your information / data.</span></p>
            <h3 dir="ltr"  >PURPOSE FOR COLLECTING, USING, STORING AND PROCESSING OF INFORMATION</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">Genio collects, uses, stores and processes Your Information for any purpose as may be permissible under applicable laws (including where the applicable law provides for such collection, usage, storage or processes in accordance with the consent of the user) and shall include the following:</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.1. to facilitate Your use of the Services;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.2. to respond to Your inquiries or fulfil Your requests for information about the various services offered on the Services;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.3. to provide You with information about services available on the Services and to send You information, materials, including any email alerts, transactions with Us and competitions and promotions that you take part in and offers, if any.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.4. to send You important information regarding the Services, changes in terms and conditions, user agreements, and policies and/or other administrative information;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.5. to send You surveys, newsletters, statistics about users, traffic patterns and marketing communications;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.6. to personalize Your experience on the Services by presenting advertisements, services and offers tailored to Your preferences;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.7. to help You address Your problems incurred on the Services including addressing any technical problems;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.8. if You avail of any service from the Services, to complete and fulfil the same.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.9. to protect the integrity and for proper administering of the Services;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.10. to conduct internal reviews and data analysis for the Services;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.11. to third parties selected by Genio as part of aggregated and anonymised statistics about users, traffic patterns etc. of Genio&rsquo;s Services(s);&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.12. to conducting academic research, surveys, analytical studies on various aspects including user behaviour, user preferences etc.;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.13. to respond to legal, judicial, quasi-judicial process and provide information to law enforcement agencies or in connection with an investigation on matters related to public safety, as permitted by law;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.14. to implement information security practices;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.15. to determine any security breaches, computer contaminant or computer virus;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.16. to investigate, prevent, or take action regarding illegal activities and suspected fraud,&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.17. to undertake forensics of the concerned computer resource as a part of investigation or internal audit;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.18. To process any job application You may submit;&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.19. to trace computer resources or any person who may have contravened, or is suspected of having or being likely to contravene, any provision of law including the Information Technology Act, 2000 that is likely to have an adverse impact on the services provided on any Services or by Genio; and&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">2.20. to enable a potential buyer or investor to evaluate the business of Genio.</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">[Individually and collectively referred to as (&ldquo;Purposes&rdquo;)]</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">You hereby agree and acknowledge that the Information so collected is for lawful purpose connected with a function or activity of Genio or any person on its behalf, and the collection of Information is necessary for the Purposes.</span></p>
            <h3 dir="ltr"  >SHARING AND DISCLOSURE OF YOUR INFORMATION</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">3.1 You hereby unconditionally agree and permit that Genio may transfer, share, disclose or part with all or any of Your Information, within and outside of the Republic of India to third party service providers / partners / body corporates or regulatory authorities &nbsp;for one or more of the Purposes or as may be required by applicable law.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">3.2. You acknowledge and agree that, to the extent permissible under applicable laws, it is adequate that when Genio transfers Your Information to any other entity within or outside Your country of residence, Genio will place contractual obligations on the transferee which will oblige the transferee to adhere to the provisions of this Privacy Policy.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">3.3. Genio may share statistical data and other details (other than Your Personal Information) without Your express or implied consent to facilitates various programmes or initiatives launched by Genio, its affiliates, agents, third party service providers, partners, body corporates or banks &amp; financial institutions, from time to time. We may be required to transfer/disclose/share Information (other than Your Personal Information) to those parties who support Our business, such as providing technical infrastructure services, analyzing how Our services are used, providing statistics services, facilitating payments, traffic analysis or conducting academic research and surveys. These affiliates and third party service providers shall adhere to confidentiality obligations consistent with this Privacy Policy. Notwithstanding the above, We may use other third parties such as a credit/debit card processing company, payment gateway, pre-paid cards etc. to enable You to make payments for availing services. When You sign up for these services, You may have the ability to save Your card details for future reference and faster future payments. In such case, We may share Your relevant Personal Information as necessary for the third parties to provide such services, including Your name, residence and email address. The processing of payments or authorization is solely in accordance with these third parties policies, terms and conditions and We are not in any manner responsible or liable to You or any third party for any delay or failure at their end in processing the payments.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">3.4 We may also share Personal Information if We believe it is necessary in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of various terms and conditions or our policies.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">3.5. We reserve the right to disclose your information when required to do so by law or regulation, or under any legal obligation or order under law or in response to a request from a law enforcement or governmental agency or judicial, quasi-judicial or any other statutory or constitutional authority or to establish or exercise our legal rights or defend against legal claims.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">3.6. You further agree that such disclosure, sharing and transfer of Your Personal Information and Non-Personal Information shall not cause any wrongful loss to You or to any third party, or any wrongful gain to Us or to any third party.&nbsp;</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">3.7. We and Our affiliates will share / sell some or all of Your personal information with another business entity should We (or Our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this Privacy Policy with respect to Your Personal Information.</span></p>
            <h3 dir="ltr"  >LINK TO OTHER SERVICES</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">4.1. Our Services may provide links to other sites. These links are provided for Your convenience only and the provision of these links does not mean that sites are related or associated with Us. Please note that these Sites have their terms of use and privacy policies. You should check their privacy policy before You submit Your Personal Information or any other data with them. We don&rsquo;t guarantee the content and the security of those sites. 4.2. We may have certain features on Our Services which may be hosted by third parties, Your interaction with such features shall be governed by the privacy policy of such third parties. 4.3. We shall not be responsible for any loss, damage, claim or expense caused as a result of You accessing these third party sites and features.</span></p>
            <h3 dir="ltr"  >SECURITY</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">5.1. We strive to ensure the security, integrity and privacy of Your Information and to protect Your Personal Information against unauthorized access or unauthorized alteration, disclosure or destruction. We adopt adequate measures to prevent unauthorized access to Your Personal Information. 5.2. We reserve the right to conduct a security review at any time to verify Your identity. You agree to provide Us all the information that We request for the security review. If You fail to comply with any security request, We reserve the right terminate Your account with Us and prohibit Your access to the Services. 5.3. We are not liable and cannot be held liable for any breach of security or for any actions of any third parties that receive Your Personal Information. 5.4. The trademarks, logos and service marks displayed on the Services (&ldquo;Marks&rdquo;) are the property of Genio or respective third parties. You are not permitted to use the Marks without the prior consent of Genio or the third party that may own the Marks 5.5. Notwithstanding anything contained in this Policy or elsewhere, We shall not be held responsible for any loss, damage or misuse of Your Personal Information, if such loss, damage or misuse is attributable to a Force Majeure Event (as defined below).</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">A &ldquo;Force Majeure Event&rdquo; shall mean any event that is beyond Our reasonable control and shall include, without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, unauthorised access to computer data and storage device, computer crashes, breach of security and encryption, etc.</span></p>
            <h3 dir="ltr"  >CHOICE/OPT-OUT</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">You agree and acknowledge that You are providing your Information out of your free will. You have an option not to provide or permit Genio to collect Your Personal Information or later on withdraw Your consent with respect to such Personal Information so provided herein by sending an email to the grievance officer or such other electronic address as may be notified to You.</span></p>
            <h3 dir="ltr"  >UPDATES TO THIS PRIVACY POLICY</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">Genio may change the data privacy practices and update this Privacy Policy as and when the need arises, and the same will be made available on the Services. But our commitment to protect the privacy of Services users will continue to remain. We suggest that you regularly check this Privacy Policy to apprise yourself of any updates. Your continued use of Services or provision of data or information thereafter will imply Your unconditional acceptance of such updates to this Privacy Policy.</span></p>
            <h3 dir="ltr"  >GRIEVANCE OFFICER</h3>
            <p dir="ltr" className="docCss"><span className="docSpan">In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">Name: Piyush Mayank</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">Address: Genio, Ittina Shivas, Agara, HSR Layout, Bangalore &ndash; 560102</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">Phone: +91 8861024466</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">Email: support@genio.app</span></p>
            <p dir="ltr" className="docCss"><span className="docSpan">Time: 9.00 am &ndash; 11.00 am</span></p>
          </div>
        </center>
        <Footer />
      </React.Fragment>
    )
  }
  return (
    data()

  );
}

export default App;